import { Metadata } from 'next';
import './globals.scss';

export const metadata: Metadata = {
  title: "Yoyo's Garden",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
